version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/pkg"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
