name: XIP CLI

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get Release
        uses: bruceadams/get-release@v1.2.0
        id: release

      - name: Get dependencies
        run: |
          cd pkg
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Create output directory
        run: |
          mkdir output

      - name: Build all versions
        run: |
          cd pkg
          GOOS=linux GOARCH=amd64 go build -trimpath -i -o ../output/x-ip_linux_amd64 .
          GOOS=windows GOARCH=amd64 go build -trimpath -i -o ../output/x-ip_windows_amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -trimpath -i -o ../output/x-ip_macos_amd64 .
          GOOS=darwin GOARCH=arm64 go build -trimpath -i -o ../output/x-ip_macos_arm64 .

      - name: Upload build artifact Linux AMD64
        uses: actions/upload-artifact@v2
        with:
          name: x-ip_linux_amd64
          path: output/x-ip_linux_amd64

      - name: Upload build artifact Windows AMD64
        uses: actions/upload-artifact@v2
        with:
          name: x-ip_windows_amd64.exe
          path: output/x-ip_windows_amd64.exe

      - name: Upload build artifact macOS AMD64
        uses: actions/upload-artifact@v2
        with:
          name: x-ip_macos_amd64
          path: output/x-ip_macos_amd64

      - name: Upload build artifact macOS ARM64
        uses: actions/upload-artifact@v2
        with:
          name: x-ip_macos_arm64
          path: output/x-ip_macos_arm64

      - name: Upload Release Asset Linux AMD64
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: output/x-ip_linux_amd64
          asset_name: x-ip_linux_amd64
          asset_content_type: application/x-executable

      - name: Upload Release Asset Windows AMD64
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: output/x-ip_windows_amd64.exe
          asset_name: x-ip_windows_amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset macOS AMD64
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: output/x-ip_macos_amd64
          asset_name: x-ip_macos_amd64
          asset_content_type: application/x-mach-binary

      - name: Upload Release Asset macOS ARM64
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: output/x-ip_macos_arm64
          asset_name: x-ip_macos_arm64
          asset_content_type: application/x-mach-binary
